server:
  port: \${PORT:0}

spring:
  application:
    name: spring-webflux
  config:
    import:
      - optional:file:${project.rootDir}/../.env[.properties]
  threads:
    virtual:
      enabled: false
  aop:
    proxy-target-class: false
  sql:
    init:
      platform: postgres
  r2dbc:
    url: \${R2DBC_DATABASE_URL}
    username: \${R2DBC_DATABASE_USERNAME}
    password: \${R2DBC_DATABASE_PASSWORD}
  datasource:
    driverClassName: org.postgresql.Driver
    url: \${JDBC_DATABASE_URL}
    username: \${JDBC_DATABASE_USERNAME}
    password: \${JDBC_DATABASE_PASSWORD}
  flyway:
    url: \${spring.datasource.url}
    user: \${spring.datasource.username}
    password: \${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0
    locations:
      - filesystem:${project.rootDir}/../db/migration
  output:
    ansi:
      enabled: always
